# Generated by Django 5.2.15 on 2026-06-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('NIT', 'NIT'), ('Pasaporte', 'Pasaporte')], default='CC', max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
