# Generated by Django 5.2.15 on 2026-06-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_patient_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ocupación'),
        ),
    ]
