# Generated by Django 5.2.15 on 2026-06-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_patient_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='eps',
            field=models.CharField(blank=True, help_text='EPS o régimen de salud al que pertenece el paciente', max_length=100, verbose_name='EPS'),
        ),
    ]
