# Generated by Django 5.2.15 on 2026-06-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_patient_eps'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='companion_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del acompañante'),
        ),
        migrations.AddField(
            model_name='patient',
            name='companion_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono del acompañante'),
        ),
    ]
