# Generated by Django 5.2.15 on 2026-06-20 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_patient_companion_name_patient_companion_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe tener entre 5 y 15 dígitos.', regex='^\\d{5,15}$')], verbose_name='N° de documento'),
        ),
    ]
